# Generated by Django 5.2.5 on 2025-08-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글들 ',
            },
        ),
    ]
